### ISSUE TITLE
tetranor-12-HETE causes server error 500

### ISSUE THREAD

**Issue by dominik-kopczynski** [lifs-tools/goslin-webapp#7] opened 2021-12-03 07:13 UTC
tetranor-12-HETE

**Comment by dominik-kopczynski** [comment] 2021-12-03 07:31
Found a potential bug on parsing tetranor-12-HETE, fixed it in jgoslin (and the other goslins, too). However, cannot verify, if the webapp problem is fixed by that.

**Comment by nilshoffmann** [comment] 2021-12-03 08:40
Exception thrown is this one:
`org.lifstools.jgoslin.domain.ConstraintViolationException: Element table cannot be computed for lipid 'tetranor-12-HETE'] with root cause
kype7  
kype7  org.lifstools.jgoslin.domain.ConstraintViolationException: Element table cannot be computed for lipid 'tetranor-12-HETE'
kype7  	at org.lifstools.jgoslin.domain.Headgroup.getElements(Headgroup.java:173)
kype7  	at org.lifstools.jgoslin.domain.LipidMolecularSpecies.getElements(LipidMolecularSpecies.java:118)
kype7  	at org.lifstools.jgoslin.domain.LipidAdduct.getElements(LipidAdduct.java:131)
kype7  	at org.lifstools.jgoslin.domain.LipidAdduct.getMass(LipidAdduct.java:107)`

**Comment by dominik-kopczynski** [comment] 2021-12-03 08:55
Thanks, should be now fixed for this lipid. However, maybe should be caught and unavailable information provided. Some lipids that we can parse cannot be translated into the recent nomenclature and thus do not have an element table internally.

**Comment by nilshoffmann** [comment] 2021-12-06 12:52
This seems to be fixed now.

**Closed by nilshoffmann** 2021-12-06 12:52 UTC
